// ICD-10 Codes commonly used in Ayurveda/Physiotherapy clinics
const icdCodes = [
  { code: "M54.2", desc: "Cervicalgia" },
  { code: "M54.5", desc: "Low back pain" },
  { code: "M54.6", desc: "Pain in thoracic spine" },
  { code: "M54.9", desc: "Dorsalgia, unspecified" },
  { code: "M54.1", desc: "Radiculopathy" },
  { code: "M54.3", desc: "Sciatica" },
  { code: "M54.4", desc: "Lumbago with sciatica" },
  { code: "M79.1", desc: "Myalgia" },
  { code: "M79.3", desc: "Panniculitis, unspecified" },
  { code: "M25.5", desc: "Pain in joint" },
  { code: "M75.1", desc: "Rotator cuff syndrome" },
  { code: "M75.0", desc: "Adhesive capsulitis of shoulder" },
  { code: "M77.1", desc: "Lateral epicondylitis (Tennis elbow)" },
  { code: "M77.0", desc: "Medial epicondylitis" },
  { code: "M65.4", desc: "Radial styloid tenosynovitis (de Quervain)" },
  { code: "M47.8", desc: "Other spondylosis" },
  { code: "M47.9", desc: "Spondylosis, unspecified" },
  { code: "M47.2", desc: "Other spondylosis with radiculopathy" },
  { code: "M51.1", desc: "Lumbar disc disorders with radiculopathy" },
  { code: "M51.2", desc: "Other specified intervertebral disc displacement" },
  { code: "M50.1", desc: "Cervical disc disorder with radiculopathy" },
  { code: "M50.2", desc: "Other cervical disc displacement" },
  { code: "M53.1", desc: "Cervicobrachial syndrome" },
  { code: "M62.8", desc: "Other specified disorders of muscle" },
  { code: "M79.2", desc: "Neuralgia and neuritis, unspecified" },
  { code: "M17.9", desc: "Osteoarthritis of knee, unspecified" },
  { code: "M17.1", desc: "Primary osteoarthritis of knee, bilateral" },
  { code: "M16.9", desc: "Osteoarthritis of hip, unspecified" },
  { code: "M19.9", desc: "Osteoarthritis, unspecified" },
  { code: "M15.0", desc: "Primary generalized osteoarthritis" },
  { code: "G43.9", desc: "Migraine, unspecified" },
  { code: "G43.0", desc: "Migraine without aura" },
  { code: "G44.1", desc: "Vascular headache" },
  { code: "G44.2", desc: "Tension-type headache" },
  { code: "R51", desc: "Headache" },
  { code: "M79.7", desc: "Fibromyalgia" },
  { code: "M72.0", desc: "Palmar fascial fibromatosis (Dupuytren)" },
  { code: "M67.4", desc: "Ganglion" },
  { code: "M76.6", desc: "Achilles tendinitis" },
  { code: "M72.2", desc: "Plantar fascial fibromatosis (Plantar fasciitis)" },
  { code: "M23.5", desc: "Chronic instability of knee" },
  { code: "S13.4", desc: "Sprain of cervical spine (Whiplash)" },
  { code: "S83.5", desc: "Sprain of cruciate ligament of knee" },
  { code: "S93.4", desc: "Sprain of ankle" },
  { code: "M70.6", desc: "Trochanteric bursitis" },
  { code: "M71.1", desc: "Other infective bursitis" },
  { code: "M71.5", desc: "Other bursitis, not elsewhere classified" },
  { code: "M10.9", desc: "Gout, unspecified" },
  { code: "M06.9", desc: "Rheumatoid arthritis, unspecified" },
  { code: "M45", desc: "Ankylosing spondylitis" },
  { code: "M35.3", desc: "Polymyalgia rheumatica" },
  { code: "G56.0", desc: "Carpal tunnel syndrome" },
  { code: "G57.0", desc: "Lesion of sciatic nerve" },
  { code: "G62.9", desc: "Polyneuropathy, unspecified" },
  { code: "I10", desc: "Essential (primary) hypertension" },
  { code: "E11.9", desc: "Type 2 diabetes mellitus without complications" },
  { code: "E78.5", desc: "Hyperlipidemia, unspecified" },
  { code: "J06.9", desc: "Acute upper respiratory infection, unspecified" },
  { code: "J20.9", desc: "Acute bronchitis, unspecified" },
  { code: "J45.9", desc: "Asthma, unspecified" },
  { code: "K21.0", desc: "Gastro-esophageal reflux disease with esophagitis" },
  { code: "K30", desc: "Functional dyspepsia" },
  { code: "K59.0", desc: "Constipation" },
  { code: "L40.0", desc: "Psoriasis vulgaris" },
  { code: "L20.9", desc: "Atopic dermatitis, unspecified" },
  { code: "L30.9", desc: "Dermatitis, unspecified" },
  { code: "R10.4", desc: "Other and unspecified abdominal pain" },
  { code: "R52", desc: "Pain, unspecified" },
  { code: "F41.1", desc: "Generalized anxiety disorder" },
  { code: "F32.9", desc: "Major depressive disorder, single episode" },
  { code: "G47.0", desc: "Insomnia" },
  { code: "N39.0", desc: "Urinary tract infection, site not specified" },
  { code: "M81.0", desc: "Age-related osteoporosis without fracture" },
  { code: "E66.9", desc: "Obesity, unspecified" },
  { code: "R73.9", desc: "Hyperglycemia, unspecified" },
  { code: "M24.5", desc: "Contracture of joint" },
  { code: "M62.4", desc: "Contracture of muscle" },
  { code: "M21.3", desc: "Wrist or foot drop (acquired)" },
  { code: "M96.1", desc: "Postlaminectomy syndrome" },
  { code: "Z96.6", desc: "Presence of orthopedic joint implants" },
  { code: "M80.0", desc: "Age-related osteoporosis with pathological fracture" },
  { code: "G54.1", desc: "Lumbosacral plexus disorders" },
  { code: "M48.0", desc: "Spinal stenosis" },
  { code: "M43.1", desc: "Spondylolisthesis" }
];

module.exports = icdCodes;
