[client]
socket=MYSQL
port=3306

[mysql]
no-beep

[mysqld]
port=3306
socket=MYSQL
basedir=C:/Program Files/MySQL/MySQL Server 8.0
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
default-storage-engine=INNODB
datadir=C:/clinc/insurance-module/mysql-data
log-error=C:/clinc/insurance-module/mysql-data/mysql-error.log
skip-networking=0
bind-address=127.0.0.1
